[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.3"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[prune]
  go-tests = true
  unused-packages = true
